### ISSUE TITLE
You might want to consider phantomjs.

### ISSUE THREAD

**Issue by InputNeuron** [bag-man/dm_bot#2]
Saw your dm_bot on reddit.

Great job.. the dailymail sucks.

I had thought of the same thing for mirroring 'clickbait' but I don't have the time to work on it.

You might want to consider phantomjs instead.

There's a command line 'render.js' which basically takes a URLs and renders it as a png.  

It is a full webkit browser so you can make it do what you want.

**Comment by bag-man** [comment]
That sounds pretty cool, we were wondering if something like that existed.
When I first made the bot I couldn't find anything apart from
Selenium/Firefox to render the page so that is what I went with.

I will check that out though, thanks for the tip!

**Comment by bag-man** [comment]
I have switched it over to PhanomJS, made life a lot better for the project!

Thanks.

**Comment by InputNeuron** [comment]
SWEET!  Glad I could help!
